version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: budgetplan-database
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Pass1234$
    ports:
      - 1433:1433