// <auto-generated />
using System;
using BudgetPlan.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetPlan.Persistence.Migrations
{
    [DbContext(typeof(BudgetPlanDbContext))]
    partial class BudgetPlanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetPlan.Domain.Entities.AccessedPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DataAccessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataAccessId");

                    b.ToTable("AccessedPersons");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.BudgetPlanBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BudgetPlanEntityId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DataAccessId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetPlanEntityId1");

                    b.HasIndex("DataAccessId1");

                    b.ToTable("BudgetPlanBases");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.BudgetPlanDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BudgetPlanBaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BudgetPlanType")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DataAccessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ExpectedAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransactionCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BudgetPlanBaseId");

                    b.HasIndex("DataAccessId");

                    b.HasIndex("TransactionCategoryId");

                    b.ToTable("BudgetPlanDetails");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.BudgetPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DataAccessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataAccessId");

                    b.ToTable("BudgetPlanEntities");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.DataAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DataAccesses");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.TransactionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BudgetPlanEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DataAccessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransactionCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BudgetPlanEntityId");

                    b.HasIndex("DataAccessId");

                    b.HasIndex("TransactionCategoryId");

                    b.ToTable("TransactionCategories");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.TransactionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Inactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("InactivatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransactionCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.HasIndex("TransactionCategoryId");

                    b.ToTable("TransactionDetails");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.AccessedPerson", b =>
                {
                    b.HasOne("BudgetPlan.Domain.Entities.DataAccess", "DataAccess")
                        .WithMany("AccessedPersons")
                        .HasForeignKey("DataAccessId");

                    b.Navigation("DataAccess");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.BudgetPlanBase", b =>
                {
                    b.HasOne("BudgetPlan.Domain.Entities.BudgetPlanEntity", null)
                        .WithMany("BudgetPlanBases")
                        .HasForeignKey("BudgetPlanEntityId1");

                    b.HasOne("BudgetPlan.Domain.Entities.DataAccess", null)
                        .WithMany("BudgetPlanBases")
                        .HasForeignKey("DataAccessId1");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.BudgetPlanDetails", b =>
                {
                    b.HasOne("BudgetPlan.Domain.Entities.BudgetPlanBase", "BudgetPlanBase")
                        .WithMany("BudgetPlanDetailsList")
                        .HasForeignKey("BudgetPlanBaseId");

                    b.HasOne("BudgetPlan.Domain.Entities.DataAccess", "DataAccess")
                        .WithMany("BudgetPlanDetails")
                        .HasForeignKey("DataAccessId");

                    b.HasOne("BudgetPlan.Domain.Entities.TransactionCategory", "TransactionCategory")
                        .WithMany("BudgetPlanDetails")
                        .HasForeignKey("TransactionCategoryId");

                    b.Navigation("BudgetPlanBase");

                    b.Navigation("DataAccess");

                    b.Navigation("TransactionCategory");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.BudgetPlanEntity", b =>
                {
                    b.HasOne("BudgetPlan.Domain.Entities.DataAccess", "DataAccess")
                        .WithMany("BudgetPlanEntities")
                        .HasForeignKey("DataAccessId");

                    b.Navigation("DataAccess");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.TransactionCategory", b =>
                {
                    b.HasOne("BudgetPlan.Domain.Entities.BudgetPlanEntity", null)
                        .WithMany("TransactionCategories")
                        .HasForeignKey("BudgetPlanEntityId");

                    b.HasOne("BudgetPlan.Domain.Entities.DataAccess", null)
                        .WithMany("TransactionCategories")
                        .HasForeignKey("DataAccessId");

                    b.HasOne("BudgetPlan.Domain.Entities.TransactionCategory", null)
                        .WithMany("SubTransactionCategories")
                        .HasForeignKey("TransactionCategoryId");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.TransactionDetail", b =>
                {
                    b.HasOne("BudgetPlan.Domain.Entities.DataAccess", "Access")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("AccessId");

                    b.HasOne("BudgetPlan.Domain.Entities.TransactionCategory", "TransactionCategory")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TransactionCategoryId");

                    b.Navigation("Access");

                    b.Navigation("TransactionCategory");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.BudgetPlanBase", b =>
                {
                    b.Navigation("BudgetPlanDetailsList");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.BudgetPlanEntity", b =>
                {
                    b.Navigation("BudgetPlanBases");

                    b.Navigation("TransactionCategories");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.DataAccess", b =>
                {
                    b.Navigation("AccessedPersons");

                    b.Navigation("BudgetPlanBases");

                    b.Navigation("BudgetPlanDetails");

                    b.Navigation("BudgetPlanEntities");

                    b.Navigation("TransactionCategories");

                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("BudgetPlan.Domain.Entities.TransactionCategory", b =>
                {
                    b.Navigation("BudgetPlanDetails");

                    b.Navigation("SubTransactionCategories");

                    b.Navigation("TransactionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
